
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0c\x81\xc6gY0"-\xee\x8f\t\xf7\x90h\xb6&'
    
_lr_action_items = {'AV2C':([32,],[34,]),'AV1O':([27,],[28,]),'MENORBARRA':([1,2,7,8,9,10,11,15,17,24,25,26,],[-6,-19,-19,-18,16,-16,-17,-15,-5,-7,-9,-8,]),'TEXT':([3,12,16,18,19,22,30,33,34,],[12,-19,21,23,-11,-10,-12,-13,-14,]),'AV2O':([27,],[29,]),'AV1C':([31,],[33,]),'IGUAL':([23,],[27,]),'MENOR':([0,1,2,4,7,8,11,17,24,25,26,],[3,-6,3,3,3,-18,-17,-5,-7,-9,-8,]),'PD':([0,1,2,6,7,8,11,13,17,24,25,26,],[4,-6,8,14,8,-18,-17,20,-5,-7,-9,-8,]),'AV2TEXT':([29,],[32,]),'AV1TEXT':([28,],[31,]),'MAYOR':([12,18,19,21,22,30,33,34,],[-19,24,-11,26,-10,-12,-13,-14,]),'BARRAMAYOR':([12,18,19,22,30,33,34,],[-19,25,-11,-10,-12,-13,-14,]),'$end':([1,5,6,13,14,17,20,25,26,],[-6,0,-1,-3,-2,-5,-4,-9,-8,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'hijo':([2,7,],[7,7,]),'A':([18,],[22,]),'especial':([0,2,4,7,],[1,1,1,1,]),'EI':([0,2,4,7,],[2,2,2,2,]),'EF':([9,],[17,]),'valorA':([27,],[30,]),'AS':([12,],[18,]),'hijos':([2,7,],[9,15,]),'root':([0,],[5,]),'empty':([2,7,12,],[10,10,19,]),'elemento':([0,2,4,7,],[6,11,13,11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root","S'",1,None,None,None),
  ('root -> elemento','root',1,'p_root_elemento','Entrega-XMLJSON.py',153),
  ('root -> elemento PD','root',2,'p_root_elemento','Entrega-XMLJSON.py',154),
  ('root -> PD elemento','root',2,'p_root_PD','Entrega-XMLJSON.py',161),
  ('root -> PD elemento PD','root',3,'p_root_PD','Entrega-XMLJSON.py',162),
  ('elemento -> EI hijos EF','elemento',3,'p_elemento','Entrega-XMLJSON.py',169),
  ('elemento -> especial','elemento',1,'p_elemento','Entrega-XMLJSON.py',170),
  ('EI -> MENOR TEXT AS MAYOR','EI',4,'p_EI','Entrega-XMLJSON.py',180),
  ('EF -> MENORBARRA TEXT MAYOR','EF',3,'p_EF','Entrega-XMLJSON.py',184),
  ('especial -> MENOR TEXT AS BARRAMAYOR','especial',4,'p_especial','Entrega-XMLJSON.py',188),
  ('AS -> AS A','AS',2,'p_AS','Entrega-XMLJSON.py',192),
  ('AS -> empty','AS',1,'p_AS','Entrega-XMLJSON.py',193),
  ('A -> TEXT IGUAL valorA','A',3,'p_A','Entrega-XMLJSON.py',201),
  ('valorA -> AV1O AV1TEXT AV1C','valorA',3,'p_valorA','Entrega-XMLJSON.py',205),
  ('valorA -> AV2O AV2TEXT AV2C','valorA',3,'p_valorA','Entrega-XMLJSON.py',206),
  ('hijos -> hijo hijos','hijos',2,'p_hijos','Entrega-XMLJSON.py',210),
  ('hijos -> empty','hijos',1,'p_hijos','Entrega-XMLJSON.py',211),
  ('hijo -> elemento','hijo',1,'p_ce','Entrega-XMLJSON.py',219),
  ('hijo -> PD','hijo',1,'p_cpd','Entrega-XMLJSON.py',223),
  ('empty -> <empty>','empty',0,'p_empty','Entrega-XMLJSON.py',227),
]
